"""added password column that would enables users to login to the page

Revision ID: da2c002a9b35
Revises: 9ed305da5ab5
Create Date: 2021-09-19 16:07:19.696056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2c002a9b35'
down_revision = '9ed305da5ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
